import { Link } from "react-router";
import "../styles/HomePage.css"; // Reuse styling
import { Helmet } from 'react-helmet-async';

export function meta() {
  return [
    { title: "Terms of Service - The Daily Newzlet" },
    { name: "description", content: "Terms of service for The Daily Newzlet." },
  ];
}

export default function TermsOfService() {
  return (
    <main className="container page-container" style={{ padding: '4rem var(--margin-mobile)' }}>
      <Helmet>
        <title>Terms of Service - The Daily Newzlet</title>
        <meta name="description" content="Terms of service for The Daily Newzlet." />
      </Helmet>
      <h1 className="text-display-md text-uppercase mb-4">Terms of Service</h1>
      <div className="neo-shadow" style={{ padding: '2rem', backgroundColor: 'var(--surface-container)' }}>
        <p className="text-body-lg mb-4">
          Newzlet is provided &apos;as is&apos; for informational purposes. By using this site, you acknowledge that we are not responsible for the accuracy, legality, or content of the external news articles linked. Additionally, certain summaries on this platform are generated by Artificial Intelligence. We make no guarantees regarding the accuracy, completeness, or reliability of these AI-generated statements.
        </p>
        <p className="text-body-lg mb-4">
          We operate under fair use by linking directly to the original source. Continued use of the site constitutes agreement to these terms.
        </p>
      </div>
    </main>
  );
}
