# Generated by Django 6.0.5 on 2026-05-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(max_length=7)),
                ('emoji', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_url', models.URLField(unique=True)),
                ('source_name', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.PositiveSmallIntegerField(default=1)),
                ('is_breaking', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', '-published_at'], name='news_articl_categor_32b688_idx'), models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['is_breaking'], name='news_articl_is_brea_cfd84b_idx')],
            },
        ),
    ]
