# Generated by Django 6.0.5 on 2026-06-07 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='news_articl_is_brea_cfd84b_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='emoji',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_breaking',
        ),
        migrations.RemoveField(
            model_name='article',
            name='read_time',
        ),
    ]
