# Generated by Django 6.0.5 on 2026-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
