# Generated by Django 6.0.5 on 2026-06-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
